import { FormData } from '../interfaces/field.interface';

const frequencyOptions = [
  { label: 'Nunca', value: 'never' },
  { label: 'Menos de una vez al mes', value: 'lessThanOnceAMonth' },
  { label: 'Una vez al mes', value: 'onceAMonth' },
  { label: 'Una vez por semana', value: 'onceAWeek' },
  { label: 'De 2 a 3 veces por semana', value: 'twoToThreeTimesAWeek' },
  { label: 'Diariamente', value: 'daily' },
];

export const antecedentesPersonalesPatologicos: FormData = {
  title: 'Antecedentes personales patológicos',
  description: 'Conteste con honestidad',
  fields: [
    {
      label: '¿Fuma?',
      key: 'smokes',
      type: 'boolean',
      cols: 2,
    },
    {
      label: '¿Con qué frecuencia fuma?',
      key: 'smokingFrequency',
      type: 'select',
      options: frequencyOptions,
      cols: 4,
    },
    {
      label: '¿Ingiere bebidas alcohólicas?',
      key: 'alcoholConsumption',
      type: 'boolean',
      cols: 2,
    },
    {
      label: '¿Con qué frecuencia ingiere bebidas alcohólicas?',
      key: 'alcoholFrequency',
      type: 'select',
      options: frequencyOptions,
      cols: 4,
    },
    {
      label: '¿Practica algún deporte?',
      key: 'practicesSports',
      type: 'boolean',
      cols: 2,
    },
    {
      label: '¿Cuales?',
      key: 'sportsDetails',
      type: 'text',
      cols: 2,
    },
    {
      label: '¿Con qué frecuencia practica deporte?',
      key: 'sportsFrequency',
      options: frequencyOptions,
      type: 'select',
      cols: 2,
    },
    {
      label: '¿Tiene alguna alergia?',
      key: 'hasAllergies',
      type: 'boolean',
      cols: 2,
    },
    {
      label: '¿Cuáles?',
      key: 'allergyDetails',
      type: 'text',
      cols: 4,
    },
    {
      label:
        'De las siguientes enfermedades, seleccione aquellas donde ha sido diagnosticado',
      key: 'diagnosedConditions',
      type: 'multiSelect',
      options: [
        { label: 'Diabetes', value: 'diabetes' },
        { label: 'VIH/SIDA', value: 'HIV' },
        { label: 'Síndrome del túnel carpiano', value: 'carpalTunnelSyndrome' },
        { label: 'Hipertensión', value: 'hypertension' },
        { label: 'Piedras en los riñones', value: 'kidneyStones' },
        { label: 'Artritis o problemas en los huesos', value: 'arthritis' },
        { label: 'Enfermedades del corazón', value: 'heartDiseases' },
        { label: 'Gastritis', value: 'gastritis' },
        { label: 'Cáncer', value: 'cancer' },
        { label: 'Colesterol alto', value: 'highCholesterol' },
        { label: 'Colitis', value: 'colitis' },
        { label: 'Cataratas', value: 'cataracts' },
        { label: 'Triglicéridos altos', value: 'highTriglycerides' },
        { label: 'Hernia en el ombligo o inguinal', value: 'hernia' },
        { label: 'Tuberculosis', value: 'tuberculosis' },
        { label: 'Depresión', value: 'depression' },
        { label: 'Problemas para escuchar', value: 'hearingProblems' },
        { label: 'Enfermedades de los oídos', value: 'earDiseases' },
        { label: 'Ansiedad', value: 'anxiety' },
        { label: 'Varices', value: 'varicoseVeins' },
        { label: 'Rinitis/Sinusitis', value: 'rhinitisSinusitis' },
        { label: 'Insomnio', value: 'insomnia' },
        { label: 'Desviación de la columna o escoliosis', value: 'scoliosis' },
        { label: 'Enfermedades del pulmón', value: 'lungDiseases' },
        { label: 'Epilepsia', value: 'epilepsy' },
        { label: 'Hernia de disco', value: 'discHernia' },
        { label: 'Asma', value: 'asthma' },
        { label: 'Esquizofrenia', value: 'schizophrenia' },
        { label: 'Astigmatismo', value: 'astigmatismo' },
        { label: 'Hepatitis', value: 'hepatitis' },
        { label: 'Migraña o dolor de cabeza', value: 'migraineHeadache' },
        { label: 'Miopía o problemas para ver de lejos', value: 'myopia' },
        { label: 'Problemas del hígado', value: 'liverProblems' },
        { label: 'Lumbalgia o dolor de espalda', value: 'lumbago' },
        {
          label: 'Hipermetropía o problemas para ver de cerca',
          value: 'hypermetropia',
        },
      ],
      cols: 6,
    },
    {
      label: 'Otras',
      key: 'otherConditions',
      type: 'text',
      cols: 6,
    },
    {
      label: '¿Le han realizado alguna cirugía?',
      key: 'surgery',
      type: 'boolean',
      cols: 2,
    },
    {
      label: 'Especificar de que y a que edad',
      key: 'surgeryDetails',
      type: 'text',
      cols: 4,
    },
    {
      label: '¿Ha tenido algun accidente?',
      key: 'accident',
      type: 'boolean',
      cols: 2,
    },
    {
      label: 'Especificar de que tipo, la edad y el tratamiento',
      key: 'accidentDetails',
      type: 'text',
      cols: 4,
    },
    {
      label: '¿Le han puesto sangre alguna vez?',
      key: 'bloodTransplant',
      type: 'boolean',
      cols: 6,
    },
    {
      label: '¿Alguna vez ha estado incapacitado mas de un mes?',
      key: 'incapacitated',
      type: 'boolean',
      cols: 2,
    },
    {
      label: 'Especifique porque',
      key: 'incapacitatedDetails',
      type: 'text',
      cols: 4,
    },
    {
      label:
        '¿En algún trabajo, posterior a un accidente, le han otorgado una incapacidad parcial permanente por secuelas?',
      key: 'incapacitatedPostIncident',
      type: 'text',
      cols: 6,
    },
    {
      label:
        '¿En este momento esta tomando algun medicamento o toma alguno de por vida?',
      key: 'medication',
      type: 'boolean',
      cols: 2,
    },
    {
      label: 'Especifique cual',
      key: 'medicationDetails',
      type: 'text',
      cols: 4,
    },
    {
      label: '¿Alguna vez ha ingerido alguna droga?',
      key: 'drugs',
      type: 'boolean',
      cols: 2,
    },
    {
      label: 'Especifique a que edad y cual',
      key: 'drugsDetails',
      type: 'text',
      cols: 4,
    },
  ],
};
